# port
server:
  port: 8001

# service name
spring:
  application:
    name: eureka-server

# host
eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: false
    register-with-eureka: false

